MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "D:\\detectron2-main\\run\\output\\model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 50
DATASETS:
  TRAIN: ("mini_deepfashion_train",)
  TEST: ("mini_deepfashion_test",)
SOLVER:
  BASE_LR: 0.000025
  STEPS: (1000, 1300)
  MAX_ITER: 500
  IMS_PER_BATCH: 5
#  WARMUP_ITERS: 100
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: "D:/detectron2-main/run/output"
VERSION: 2